version: "3.6"

services:
  app:
    image: ${IMAGE_APP}
    ports:
      - ${APP_PORT}:9900
    volumes:
      - ./src/config.docker.yaml:/root/config.yaml
    entrypoint: ["krohobor", "httpserver"]
    restart: on-failure
    links:
      - postgres-source

  postgres-source:
    image: ${IMAGE_POSTGRES}
    restart: always
    volumes:
      - krohobor-postgres-source:/var/lib/postgresql/data
      - ./database/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  postgres-target:
    image: ${IMAGE_POSTGRES}
    restart: always
    volumes:
      - krohobor-postgres-target:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  krohobor-postgres-source:
  krohobor-postgres-target:
