version: "3.6"

services:
  app:
    image: ${IMAGE_APP}
    ports:
      - ${APP_PORT}:80
    environment:
      APP_PORT: 80
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
    links:
      - postgres

  postgres:
    image: ${IMAGE_POSTGRES}
    restart: always
    volumes:
      - krohobor-postgres:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

  ppa:
    image: ${IMAGE_PPA}
    restart: always
    ports:
      - 7051:80
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
    links:
      - postgres

volumes:
  krohobor-postgres:
