name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set tag
        id: tag
        run: echo "::set-output name=tag::$(git tag -l --points-at HEAD | cut -d "v" -f 2)"
      - name: Check tag
        run: echo ${{ steps.tag.outputs.tag }}
      - name: Check tag2
        run:  if [ ! -z "${{ steps.tag.outputs.tag }}" ]; then echo ${{ steps.tag.outputs.tag }}; fi
