name: CI

on: [push]

jobs:
  tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Set tag
        uses: actions/checkout@v3
        id: tag
        run: echo "tag=$(git tag -l --points-at HEAD | cut -d "v" -f 2)" >> $GITHUB_OUTPUT

      - name: Check tag
        run: echo ${{ steps.tag.outputs.tag }}
