name: CI

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unit tests
        run: cd src && go test ./... -v

  image_test:
    runs-on: ubuntu-20.04
    needs: [unit_test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2
      - name: Copy config
        run: cp .env.example .env
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Image tests
        run: cd tests && go test ./... -v

  push:
    runs-on: ubuntu-20.04
    needs: [image_test]
    steps:
      - uses: actions/checkout@v1
      - name: Build & Push krohobor to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gurkalov/krohobor
          tags: ${{ github.sha }}
          dockerfile: Dockerfile
          username: gurkalov
          password: ${{ secrets.DOCKER_PASSWORD }}
